FROM balenalib/aarch64-ubuntu:bionic-build
WORKDIR /vpp
RUN apt-get update;apt-get install -y make git sudo moreutils
ADD ["./Makefile","/vpp"]
ADD ["./build-data/deps.mk","/vpp/build-data/deps.mk"]
RUN make UNATTENDED=yes install-dep | ts
ADD [".","/vpp"]
RUN make -j 16 UNATTENDED=yes verify | ts